```{r include = FALSE}
#tidyverse_packages()

#install.packages("devtools")
#devtools::install_github("r-lib/conflicted")
library(conflicted)

### Bioconductor and CRAN libraries used
library(tidyverse)
library(readr)
library(tidyr)
library(stringr)
#install.packages("BiocManager")
#BiocManager::install("AnnotationHub")
#BiocManager::install("ensembldb")
library(AnnotationHub) # bioc
#install.packages("restfulr")
library(restfulr)
library(ensembldb) # bioc
library(RColorBrewer)

#BiocManager::install("DESeq2")
library(DESeq2)
library(pheatmap) # R
#BiocManager::install("DEGreport")
#BiocManager::install("tximport")
library(DEGreport) # bioc
library(tximport) # bioc
library(ggplot2) 
library(ggrepel) #r
library(knitr)

library(ggplotify)#r
library(writexl) #r

#BiocManager::install("clusterProfiler")
#BiocManager::install("org.Mm.eg.db")
library(clusterProfiler) #bioc
library(org.Mm.eg.db) # bioc

ggplot2::theme_set(theme_light(base_size = 14))

opts_chunk[["set"]](
    cache = FALSE,
    dev = c("png", "pdf"),
    error = TRUE,
    highlight = TRUE,
    message = FALSE,
    prompt = FALSE,
    tidy = FALSE,
    warning = FALSE)

#install.packages(pacman)

```

```{r}
counts_csv <- "GSE97356/raw_counts.csv"
counts_raw <- read.csv(counts_csv, row.names = 1)

metadata_tsv <- "GSE97356/metadata.csv"
metadata <- read.csv(metadata_tsv, row.names = 1)
metadata <- t(metadata) %>% as.data.frame()
#str_replace_all(metadata["Sample_group"], c("ptsd: Past" = "past", "ptsd: Current" = "current", "ptsd: Never" = "control"))
```

```{r}
dds_file <- "GSE97356/dds.RDS"
dds_dataset <- DESeqDataSetFromMatrix(countData = counts_raw, 
                              colData = metadata, 
                              design = ~Sample_group)
keep <- rowMeans(counts(dds_dataset)) >= 100
dds_dataset <- dds_dataset[keep, ]
dds <- DESeq(dds_dataset)
#saveRDS(dds, dds_file)
```

# Sample-level QC analysis 
```{r include = FALSE}
### Transform counts for data visualization (unsupervised analysis)
rld_file <- "GSE97356/rld.RDS"
rld <- vst(dds)
#saveRDS(rld, rld_file)

# we also need just a matrix of transformed counts
#rld_mat <- assay(rld)
```
# PCA
```{r, fig.width = 10, fig.height = 10}
plotPCA(rld, intgroup = c("Sample_group"), ntop = 500) + 
  geom_label_repel(aes(label = name)) + 
  theme_bw()
#BiocManager::install("PCAtools")
#library(PCAtools)
#p = pca(counts_raw, metadata = metadata)
#plotloadings(p, drawConnectors = TRUE)
```

## Differential testing: multigroup

```{r, fig.width = 10, fig.height = 5}
dds_lrt <- DESeq(dds_dataset, test="LRT", reduced = ~ 1)

res_lrt <- results(dds_lrt) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column(var="gene_id") %>% 
  as_tibble()%>%
  arrange(padj)

intercept_genes_sig <- res_lrt %>% 
  dplyr::filter(padj < 0.05) %>%
  #arrange(padj) %>%
  head(n=3000)

intercept_preprocessed <- assay(dds)[intercept_genes_sig$gene_id, ]

intercept_preprocessed <- varianceStabilizingTransformation(intercept_preprocessed)

dim(intercept_preprocessed)

metadata <- as.data.frame(metadata)

metadata$Sample_group <- factor(metadata$Sample_group, levels = c("never", "current", "past"))


clusters_intercept <- degPatterns(intercept_preprocessed, metadata = metadata, time = "Sample_group", , col=NULL)

groups_intercept <- clusters_intercept$df

write.csv(groups_intercept, "GSE97356/clusters.csv")
```

# DE

```{r}
pacman::p_load("ashr")

contrast_cn <- c("Sample_group", "current", "never")
res_ashr_cn <- results(dds, contrast = contrast_cn)
res_shrink_cn <- lfcShrink(dds, type="ashr", contrast = c("Sample_group", "current", "never"))

res_sig_ashr_cn <- res_ashr_cn %>% as.data.frame() %>% dplyr::filter(padj < 0.05, abs(log2FoldChange) > 0.27)
#res_shrink_sig_cn <- res_shrink_cn %>% as.data.frame() %>% dplyr::filter(padj < 0.05, abs(log2FoldChange) > 0.27)

#hist(res_ashr_cn$log2FoldChange, 100)

contrast_pn <- c("Sample_group", "past", "never")
res_ashr_pn <- results(dds, contrast = contrast_pn)
#res_shrink_pn <- lfcShrink(dds, type="ashr", contrast = c("Sample_group", "current", "never"))

res_sig_ashr_pn <- res_ashr_pn %>% as.data.frame() %>% dplyr::filter(padj < 0.05, abs(log2FoldChange) > 0.27)
#res_shrink_sig_pn <- res_shrink_pn %>% as.data.frame() %>% dplyr::filter(padj < 0.05, abs(log2FoldChange) > 0.27)

#hist(res_ashr_pn$log2FoldChange, 100)

contrast_cp <- c("Sample_group", "past", "never")
res_ashr_cp <- results(dds, contrast = contrast_cp)
#res_shrink_cp <- lfcShrink(dds, type="ashr", contrast = c("Sample_group", "current", "never"))

res_sig_ashr_cp <- res_ashr_cp %>% as.data.frame() %>% dplyr::filter(padj < 0.05, abs(log2FoldChange) > 0.27)
#res_shrink_sig_cp <- res_shrink_cp %>% as.data.frame() %>% dplyr::filter(padj < 0.05, abs(log2FoldChange) > 0.27)

#hist(res_ashr_cp$log2FoldChange, 100)
```

## Volcano plots

```{r, fig.width = 10, fig.height = 7}
#BiocManager::install("EnhancedVolcano")
library(EnhancedVolcano)
volcano_cn <- res_ashr_cn %>% as.data.frame()
EnhancedVolcano(volcano_cn,
                lab = rownames(volcano_cn),
                x = "log2FoldChange",
                y = "padj",
                title = 'Volcano plot current/never',
                pCutoff = 0.05,
                FCcutoff = 0.27) + 
          ggplot2::coord_cartesian(xlim=c(-1, 1), ylim = c(0,3)) + 
          ggplot2::scale_x_continuous(breaks=seq(-1,1, 1)) + 
          ggplot2::scale_y_continuous(breaks=seq(0,3, 1))

volcano_pn <- res_ashr_pn %>% as.data.frame()
EnhancedVolcano(volcano_pn,
                lab = rownames(volcano_pn),
                x = "log2FoldChange",
                y = "padj",
                title = 'Volcano plot past/never',
                pCutoff = 0.05,
                FCcutoff = 0.27) + 
          ggplot2::coord_cartesian(xlim=c(-1, 1), ylim = c(0,3)) + 
          ggplot2::scale_x_continuous(breaks=seq(-1,1, 1)) + 
          ggplot2::scale_y_continuous(breaks=seq(0,3, 1))

volcano_cp <- res_ashr_cp %>% as.data.frame()
EnhancedVolcano(volcano_cp,
                lab = rownames(volcano_cp),
                x = "log2FoldChange",
                y = "padj",
                title = 'Volcano plot current/past',
                pCutoff = 0.05,
                FCcutoff = 0.27) + 
          ggplot2::coord_cartesian(xlim=c(-1, 1), ylim = c(0,3)) + 
          ggplot2::scale_x_continuous(breaks=seq(-1,1, 1)) + 
          ggplot2::scale_y_continuous(breaks=seq(0,3, 1))
```


```{r, fig.width = 10, fig.height = 7 }
counts_csv <- "GSE97356/raw_counts.csv"
counts_raw <- read.csv(counts_csv, row.names = 1)

metadata_tsv <- "GSE97356/metadata.csv"
metadata <- read.csv(metadata_tsv, row.names = 1)
metadata <- t(metadata) %>% as.data.frame()

res_sig_ashr_cn <- read.csv("GSE97356/res_sign_cn_ashr.csv", row.names = 1)

dds_dataset <- DESeqDataSetFromMatrix(countData = counts_raw, 
                              colData = metadata, 
                              design = ~Sample_group)
keep <- rowMeans(counts(dds_dataset)) >= 100
dds_dataset <- dds_dataset[keep, ]

metadata$Sample_group <- factor(metadata$Sample_group, levels = c("never", "current", "past"))
metadata <- metadata %>% as.data.frame() %>% arrange(Sample_group)
metadata_sample_group <- metadata %>% dplyr::select(Sample_group) 

rld <- vst(dds_dataset, blind = TRUE)
#rld <- vst(dds, blind = TRUE)
#sig_gene_names <- c(rownames(res_sig_ashr_cn), "GRB10")
sig_gene_names <- rownames(res_sig_ashr_cn)
counts_assay <- assay(rld) %>% as.data.frame()
sig_counts <- counts_assay[rownames(counts_assay) %in% sig_gene_names, ]
sig_counts <- sig_counts[,metadata_sample_group$Sample_group]

sig_counts_scaled <- t(scale(t(sig_counts)))

#counts_vst <- assay(rld) %>% as.data.frame()
#matrix_correlations <- cor(counts_vst)

pheatmap(
  #matrix_correlations,
  sig_counts_scaled,
  annotation = metadata_sample_group, 
  cluster_rows = TRUE, 
  cluster_cols = FALSE,
  show_rownames = TRUE, 
  show_colnames = FALSE
  )

```

```{r}
write.csv(res_sig_ashr_cn, "GSE97356/res_sign_cn_ashr.csv")
write.csv(res_sig_ashr_cp, "GSE97356/res_sign_cp_ashr.csv")
write.csv(res_sig_ashr_pn, "GSE97356/res_sign_cp_ashr.csv")
```

```{r, fig.width = 10, fig.height = 7}
pacman::p_load("here", "tidyverse", "enrichR", "gprofiler2")

plot_enrichr_results <- function(enrichr_results, pval_threshold = 0.05, top_n = 10, fill_column = "Combined.Score") {

  filtered_results <- enrichr_results %>%
    dplyr::filter(Adjusted.P.value <= pval_threshold) %>%
    arrange(Adjusted.P.value) %>%
    head(top_n)
  
  p <- ggplot(filtered_results, aes(x = reorder(Term, -Adjusted.P.value), 
                                    y = -log10(Adjusted.P.value), 
                                    fill = !!sym(fill_column))) +
    geom_bar(stat = "identity") +
    scale_fill_gradient(low = "#00b1b1", high = "#9f0077") +
    coord_flip() +
    theme_minimal() +
    labs(title = "Top Enrichment Terms",
         x = "Enrichment Term",
         y = "-log10(Adjusted P-value)",
         fill = fill_column) +
    theme(axis.text = element_text(size = 12),
          axis.title = element_text(size = 14),
          plot.title = element_text(size = 16, face = "bold"))
  
  print(p)
}

de_results <- res_sig_ashr_cn
dbs <- listEnrichrDbs()
dbs <- c("GO_Molecular_Function_2023", "GO_Biological_Process_2023", "GO_Cellular_Component_2023")

enriched_up <- enrichr(rownames(de_results %>% dplyr::filter(log2FoldChange > 0) %>%arrange(desc(log2FoldChange))), dbs)

enriched_down <- enrichr(rownames(de_results %>% dplyr::filter(log2FoldChange < 0) %>%arrange(log2FoldChange)), dbs)

pu_BP <- plot_enrichr_results(enriched_up$GO_Biological_Process_2023) + ggtitle("BP up regulated")

pd_BP <- plot_enrichr_results(enriched_down$GO_Biological_Process_2023) + ggtitle("BP down regulated")

enriched <- enrichr(rownames(de_results), dbs)
pt_BP <- plot_enrichr_results(enriched$GO_Biological_Process_2023) + ggtitle("BP total")
#cowplot::plot_grid(pu_BP, pd_BP, pt_BP, ncol=3, labels=LETTERS[1:3])
```

```{r, fig.width = 10, fig.height = 10}
gostres <- gost(query = c(rownames(res_sig_ashr_cn), "GRB10"), organism = "hsapiens",
    ordered_query = TRUE)

gostres_res <- gostres$result

p <- gostplot(gostres, capped = FALSE, interactive = FALSE)
pathways <- (gostres_res %>% arrange(p_value))$term_id
publish_gostplot(p,  highlight_terms = pathways)
```
# Visualization - Gene example

```{r, fig.width=12, fig.height = 12}
pacman::p_load("here", "tidyverse", "gridExtra", "ggvenn")

gene_plot <- function(dds, gene_name) {
  d <- plotCounts(dds, 
                gene = gene_name, 
                intgroup = "Sample_group", 
                returnData = TRUE)

  p <- ggplot(d, aes(x = Sample_group, y = count, color = Sample_group)) + 
       geom_point(position = position_jitter(w = 0.1, h = 0)) +
       geom_text_repel(aes(label = rownames(d))) + 
       theme_bw(base_size = 10) +
       ggtitle(gene_name) +
       theme(plot.title = element_text(hjust = 0.5)) +
       scale_y_log10()
  return(p)
}

gene_names <- res_sig_ashr_cn %>% arrange(log2FoldChange) %>% rownames()
plot_list <- list()
for (gene in gene_names) {
  p <- gene_plot(dds, gene)
  plot_list <- plot_list %>% append(p)
  print(p)
}
#cowplot::plot_grid(plot_list[1], plot_list[2])

#conflicts_prefer(dplyr::combine)
#grid.arrange(plot_list[1], plot_list[2])
#GRB10
```

```{r}
pacman::p_load("here", "clusterProfiler", "biomaRt", "stats", "dplyr", 
               "enrichplot", "europepmc", "janitor", "org.Hs.eg.db")
ensembl <- useMart('ensembl', dataset = 'hsapiens_gene_ensembl')

genes_entrez <- getBM(filters = "external_gene_name",
             attributes = c('hgnc_symbol', "external_gene_name", "entrezgene_id"),
             values = rownames(res_shrink),
             mart = ensembl)
de_results <- res_shrink %>% 
  mutate(ranking = (sign(log2FoldChange) * (-log10(pvalue)))) %>% 
  arrange(desc(ranking)) %>% tibble::rownames_to_column("genes")

de_results <- dplyr::left_join(de_results, genes_entrez, by = c("genes" = "external_gene_name"))

de_results %>% janitor::get_dupes("entrezgene_id")

de_results <- de_results %>%
  tidyr::drop_na() %>%
  dplyr::distinct(entrezgene_id, .keep_all = TRUE)


genes_list <- de_results$ranking
names(genes_list) <- de_results$entrezgene_id
genes_list = sort(genes_list, decreasing = TRUE)

gseGO_res_005 <- gseGO(geneList = genes_list,
              OrgDb = org.Hs.eg.db,
              ont = "BP",
              pvalueCutoff = 0.05,
              )
gseGO_res_005_genename <- setReadable(gseGO_res_005, 'org.Hs.eg.db', 'ENTREZID')
dotplot(gseGO_res_005, showCategory=20, x = "NES", color = "NES") + ggtitle("dotplot for GSEA 0.05")
```
```{r}
## categorySize can be scaled by 'pvalue' or 'geneNum'
p2 <- cnetplot(gseGO_res_005_genename, categorySize="pvalue", 
               color.params = list(foldChange = genes_list))
p2
```

```{r}
p3 <- cnetplot(gseGO_res_005_genename, 
               color.params = list(foldChange = genes_list), 
               circular = TRUE, colorEdge = TRUE)
p3
```

```{r}
p4 <- cnetplot(gseGO_res_005_genename, node_label="category", 
        cex_label_category = 1.2) 
p4
```

```{r}
p5 <- cnetplot(gseGO_res_005_genename, node_label="gene", 
        cex_label_gene = 0.8) 
p5
```

```{r}
p6 <- cnetplot(gseGO_res_005_genename, node_label="all")
p6
```

```{r}
p7 <- cnetplot(gseGO_res_005_genename, node_label="none", 
        color_category='firebrick', 
        color_gene='steelblue') 
p7
```
```{r}
#res_sig_ashr_cn <- read.csv("GSE97356/res_sign_cn_ashr.csv", row.names = 1)
de_res_sig <- res_sig_ashr_cn %>% 
  mutate(ranking = (sign(log2FoldChange) * (-log10(pvalue)))) %>% 
  arrange(desc(ranking)) %>% tibble::rownames_to_column("genes")

de_res_sig <- dplyr::left_join(de_res_sig, genes_entrez, by = c("genes" = "external_gene_name"))

de_res_sig %>% janitor::get_dupes("entrezgene_id")

de_res_sig <- de_res_sig %>%
  tidyr::drop_na() %>%
  dplyr::distinct(entrezgene_id, .keep_all = TRUE)


genes_list_sig <- de_res_sig$ranking
names(genes_list_sig) <- de_res_sig$entrezgene_id
genes_list_sig = sort(genes_list_sig, decreasing = TRUE)

gseGO_res_sig <- gseGO(geneList = genes_list_sig,
              OrgDb = org.Hs.eg.db,
              ont = "BP",
              pvalueCutoff = 0.05,
              )
gseGO_res_sig_genename <- setReadable(gseGO_res_sig, 'org.Hs.eg.db', 'ENTREZID')

cnetplot(gseGO_res_sig_genename, node_label="category", 
        cex_label_category = 1.2) 
```

```{r}
cnetplot(gseWP_res_025_genename, node_label="gene", 
        cex_label_gene = 0.8) 
```

```{r}
cnetplot(gseWP_res_025_genename, node_label="all")
```

```{r}
p7 <- cnetplot(gseWP_res_025_genename, node_label="none", 
        color_category='firebrick', 
        color_gene='steelblue') 
p7
```
