```{r include = FALSE}
#tidyverse_packages()

#install.packages("devtools")
#devtools::install_github("r-lib/conflicted")
library(conflicted)

### Bioconductor and CRAN libraries used
library(tidyverse)
library(readr)
library(tidyr)
library(stringr)
#install.packages("BiocManager")
#BiocManager::install("AnnotationHub")
#BiocManager::install("ensembldb")
library(AnnotationHub) # bioc
#install.packages("restfulr")
library(restfulr)
library(ensembldb) # bioc
library(RColorBrewer)

#BiocManager::install("DESeq2")
library(DESeq2)
library(pheatmap) # R
#BiocManager::install("DEGreport")
#BiocManager::install("tximport")
library(DEGreport) # bioc
library(tximport) # bioc
library(ggplot2) 
library(ggrepel) #r
library(knitr)

library(ggplotify)#r
library(writexl) #r

#BiocManager::install("clusterProfiler")
#BiocManager::install("org.Mm.eg.db")
library(clusterProfiler) #bioc
library(org.Mm.eg.db) # bioc

ggplot2::theme_set(theme_light(base_size = 14))

opts_chunk[["set"]](
    cache = FALSE,
    dev = c("png", "pdf"),
    error = TRUE,
    highlight = TRUE,
    message = FALSE,
    prompt = FALSE,
    tidy = FALSE,
    warning = FALSE)

```

```{r}
counts_csv <- "raw_counts.tsv"
#counts_raw <- read.csv(counts_csv, sep = "\t", row.names = 1)
    counts_raw <- read.csv(counts_csv,  sep = "\t") 
    colnames(counts_raw)[1] <- "gene_name"
    #counts_tpm <- read_csv(counts_tpm_csv)
    
    # use Ensembl_Gene_id
    # remove genes with NA
    # filter protein coding genes

    annotation <- read_csv("annot.csv")
    
    annotation <- dplyr::select(annotation, c("GeneID", "Symbol", "Length"))
    
    counts_prepared <- counts_raw %>% 
            left_join(annotation, by = c("gene_name" = "GeneID")) %>%
           dplyr::select(-gene_name) %>% 
            dplyr::rename("gene_id" = "Symbol")%>%
            relocate(gene_id)
    counts_prepared <-  counts_prepared[!apply(counts_prepared, 1, function(row) any(row == 'negative')), ]

    print(which(duplicated(counts_prepared$gene_id)))
    counts_prepared <- counts_prepared[-which(duplicated(counts_prepared$gene_id)), ]
    #counts_prepared <-  counts_prepared[!apply(counts_prepared, 1, function(row) any(row == 'TRNAV-CAC')), ]

    
    v_len <- dplyr::select(counts_prepared, c("gene_id", "Length")) %>% as.data.frame()
    
          
        counts <- counts_prepared %>% arrange(gene_id)
        counts <- dplyr::select(counts, -Length)  %>% as.data.frame()
        
        counts <- counts %>% column_to_rownames("gene_id")
        
        x <- counts / as.numeric(v_len$Length)
        counts_tpm <- t(t(x) * 1e6 / colSums(x)) %>% 
          as.data.frame() %>% round(2) 
        write.csv(counts_tpm, "counts_tpm")
          #rownames_to_column("gene_id") %>% 
        
          #left_join(gene_symbol, by = c("ensembl_gene_id" = "gene_id")) %>% 
          #write_csv(counts_tpm_csv)
        counts_raw <- counts
```

```{r}
metadata_tsv <- "metadata.tsv"
metadata <- read.csv(metadata_tsv, sep = "\t", row.names = 1)
metadata <- as.data.frame(t(metadata))
```
```{r}
dds_file <- "dds.RDS"
dds_dataset <- DESeqDataSetFromMatrix(countData = counts_raw, 
                              colData = metadata, 
                              design = ~Sample_group)
keep <- rowMeans(counts(dds_dataset)) >= 100
dds_dataset <- dds_dataset[keep, ]
dds <- DESeq(dds_dataset)
saveRDS(dds, dds_file)
```

# Sample-level QC analysis 
```{r include = FALSE}
### Transform counts for data visualization (unsupervised analysis)
rld_file <- "rld.RDS"
rld <- vst(dds)
saveRDS(rld, rld_file)
```
# PCA
```{r, fig.width = 10, fig.height = 10}
plotPCA(rld, ntop = 1200, intgroup = c("Sample_group")) + 
  geom_label_repel(aes(label = name)) + 
  theme_bw()
```
# DE

```{r, , fig.width = 10, fig.height = 5}
pacman::p_load("ashr")

contrast <- c("Sample_group", "positive", "negative")
res_ashr <- results(dds, contrast = contrast) %>% as.data.frame()
res_shrink <- lfcShrink(dds, type="ashr", contrast = c("Sample_group", "positive", "negative")) %>% as.data.frame()

res_sig_ashr <- res_ashr  %>% dplyr::filter(pvalue < 0.05, abs(log2FoldChange) > 0.27)
res_shrink_sig <- res_shrink %>% dplyr::filter(pvalue < 0.05, abs(log2FoldChange) > 0.27)

hist(res_ashr$log2FoldChange, 100)
```

## Volcano plots

```{r, fig.width = 10, fig.height = 7}
#BiocManager::install("EnhancedVolcano")
library(EnhancedVolcano)
volcano <- res_ashr %>% as.data.frame()
EnhancedVolcano(volcano,
                lab = rownames(volcano),
                x = "log2FoldChange",
                y = "pvalue",
                title = 'Volcano plot current/never',
                pCutoff = 0.05,
                FCcutoff = 0.27) + 
          ggplot2::coord_cartesian(xlim=c(-1, 1), ylim = c(0,3)) + 
          ggplot2::scale_x_continuous(breaks=seq(-1,1, 1)) + 
          ggplot2::scale_y_continuous(breaks=seq(0,3, 1))
```

#heatmap
```{r, fig.width = 10, fig.height = 7 }

metadata$Sample_group <- factor(metadata$Sample_group, levels = c("positive", "negative"))
metadata_sample_group <- metadata %>% dplyr::select(Sample_group)

rld <- vst(dds_dataset, blind = TRUE)
#rld <- vst(dds, blind = TRUE)
sig_gene_names <- rownames(res_sig_ashr)
counts_assay <- assay(rld) %>% as.data.frame()
sig_counts <- counts_assay[rownames(counts_assay) %in% sig_gene_names, ]

#sig_counts_scaled <- t(scale(t(sig_counts)))
#counts_vst <- assay(rld) %>% as.data.frame()
#matrix_correlations <- cor(counts_vst)

pheatmap(
  #matrix_correlations,
  sig_counts,
  annotation = metadata_sample_group,
  show_rownames = TRUE, 
  show_colnames = FALSE
  )

write.csv(res_sig_ashr, "res_sign_ashr.csv")

```

```{r, fig.width = 10, fig.height = 7}
pacman::p_load("here", "tidyverse", "enrichR", "gprofiler2")

plot_enrichr_results <- function(enrichr_results, pval_threshold = 0.05, top_n = 10, fill_column = "Combined.Score") {

  filtered_results <- enrichr_results %>%
    dplyr::filter(Adjusted.P.value <= pval_threshold) %>%
    arrange(Adjusted.P.value) %>%
    head(top_n)
  
  p <- ggplot(filtered_results, aes(x = reorder(Term, -Adjusted.P.value), 
                                    y = -log10(Adjusted.P.value), 
                                    fill = !!sym(fill_column))) +
    geom_bar(stat = "identity") +
    scale_fill_gradient(low = "#00b1b1", high = "#9f0077") +
    coord_flip() +
    theme_minimal() +
    labs(title = "Top Enrichment Terms",
         x = "Enrichment Term",
         y = "-log10(Adjusted P-value)",
         fill = fill_column) +
    theme(axis.text = element_text(size = 12),
          axis.title = element_text(size = 14),
          plot.title = element_text(size = 16, face = "bold"))
  
  print(p)
}

de_results <- res_sig_ashr
dbs <- listEnrichrDbs()
dbs <- c("GO_Molecular_Function_2023", "GO_Biological_Process_2023", "GO_Cellular_Component_2023")

enriched_up <- enrichr(rownames(de_results %>% dplyr::filter(log2FoldChange > 0) %>%arrange(desc(log2FoldChange))), dbs)

enriched_down <- enrichr(rownames(de_results %>% dplyr::filter(log2FoldChange < 0) %>%arrange(log2FoldChange)), dbs)

plot_enrichr_results(enriched_up$GO_Biological_Process_2023)

#plot_enrichr_results(enriched_down$GO_Biological_Process_2023)

enriched <- enrichr(rownames(de_results), dbs)
plot_enrichr_results(enriched$GO_Biological_Process_2023)
```

```{r}
pacman::p_load("here", "tidyverse", "enrichR", "gprofiler2")
gostres <- gost(query = c(rownames(res_sig_ashr)), organism = "hsapiens",
    ordered_query = TRUE)

gostres_res <- gostres$result

p <- gostplot(gostres, capped = FALSE, interactive = FALSE)
p
gost_csv <- gostres_res %>% as.data.frame() %>% rownames_to_column("number") %>% column_to_rownames("number")
write.csv(gost_csv, "gostres.csv")
#publish_gostplot(p, highlight_terms = c("GO:1900028", "GO:0034702", "GO:0005886", "TF:M10157", "TF:M11515_1"))
```
# Visualization - Gene example

```{r, fig.width=12, fig.height = 12}
pacman::p_load("here", "tidyverse", "gridExtra", "ggvenn")

gene_plot <- function(dds, gene_name) {
  d <- plotCounts(dds, 
                gene = gene_name, 
                intgroup = "Sample_group", 
                returnData = TRUE)

  p <- ggplot(d, aes(x = Sample_group, y = count, color = Sample_group)) + 
       geom_point(position = position_jitter(w = 0.1, h = 0)) +
       geom_text_repel(aes(label = rownames(d))) + 
       theme_bw(base_size = 10) +
       ggtitle(gene_name) +
       theme(plot.title = element_text(hjust = 0.5)) +
       scale_y_log10()
    print(p)
}

#gene_plot(dds, "UNC45B")
```